/**
 * WRITE A FUNCTION CALLED COUNT_ZERO WHICH WILL TAKE A BINARY STRING (BINARY STRING IS A STRING WHICH IS CONSIST OF ONLY 0 AND 1) AS PARAMETER AND COUNT HOW MANY 0'S ARE THERE IN THAT STRING.
 */

function count_zero(binaryString){
    
}